# -*- coding: utf-8 -*-
"""03_Cortisol+_Cytokines_SAureus.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Hw97rVuzIkmXQnOr3KIQK8Yh7tqXyCTz
"""

from scipy.integrate import odeint
import matplotlib.pyplot as plt
import numpy as np
import math

"""## Mathematical model of the immune response activation including cortisol and glucose dynamics


#### Obs: All the rates are represented per day

## Parameters by Brady et al., (2016):
"""

n_106 = 560            # pg/mL    # Half-maximum value associated with upregulation of IL-10 by IL-6
n_610 = 34.8           # pg/mL    # Half-maximum value associated with downregulation of IL-6 by IL-10
n_66 = 560             # pg/mL    # Half-maximum value associated with the auto-negative feedback of IL-6
n_6TNF = 185           # pg/mL    # Half-maximum value associated with upregulation of IL-6 by TNF-a
n_TNF6 = 560           # pg/mL    # Half-maximum value associated with downregulation of TNF-a by IL-6
n_810 = 17.4           # pg/mL    # Half-maximum value associated with downregulation of IL-8 by IL-10
n_8TNF = 185           # pg/mL    # Half-maximum value associated with upregulation of IL-8 by TNF-a
n_M10 = 4.35           # pg/mL    # 
n_TNF10 = 17.4         # pg/mL    # Half-maximum value associated with downregulation of TNF-a by IL-10
n_MTNF = 0.1           # ?        #  
h_106 = 3.68           # -        # Hill function exponent associated with upregulation of IL-10 by IL-6
h_610 = 4              # -        # Hill function exponent associated with downregulation of IL-6 by IL-10
h_66 = 1               # -        # Hill function exponent associated with auto-negative feedback of IL-6
h_6TNF = 2             # -        # Hill function exponent associated with upregulation of IL-6 by TNF-a
h_TNF6 = 2             # -        # Hill function exponent associated with downregulation of TNF-a by IL-6
h_810 = 1.5            # -        # Hill function exponent associated with downregulation of IL-8 by IL-10
h_8TNF = 3             # -        # Hill function exponent associated with upregulation of IL-8 by TNF-a
h_M10 = 0.3            # -        # 
h_TNF10 = 3            # -        # Hill function exponent associated with downregulation of TNF-a by IL-10
h_MTNF = 3.16          # -        # 
k_MA = 2.51            #          # 
k_MR = 6               #          # 
k_m = 0.0414           #          # 
k_106 = 0.0191         # relative cytokine concentration/(day · # of cells)    # Upregulation of IL-10 by IL-6
k_6 = 4.64             # day-1                                                 # Activation rate (per hour) of IL-6
k_6m = 0.01            # relative cytokine concentration/(day · # of cells)    # Upregulation of IL-6 by the activated macrophages
k_6TNF = 0.81          # relative cytokine concentration/(day · # of cells)    # Upregulation of IL-6 by TNF-a
k_8 = 0.464            # day-1                                                 # Activation rate (per hour) of IL-8
k_8m = 0.056           # relative cytokine concentration/(day · # of cells)    # Upregulation of IL-8 by the activated macrophages
k_8TNF = 0.56          # relative cytokine concentration/(day · # of cells)    # Upregulation of IL-8 by TNF-a
k_10 = 1.1             # day-1                                                 # Activation rate (per hour) of IL-10
k_10m = 0.19           # relative cytokine concentration/(day · # of cells)    # Upregulation of IL-10 by the activated macrophages
k_TNF = 200            # day–1                                                 # Activation rate (per hour) of TNF-a
k_TNFM = 1.5           # relative cytokine concentration/(day · # of cells)    # Upregulation of TNF-a by the activated macrophages
k_MTNF = 8.65          # hr-1                                                  # Activation rate of resting macrophages influenced by
q_IL6 = 0.6            # relative concentration                                # The concentration of IL-6 in the absence of a pathogen
q_IL8 = 0.2            # relative concentration                                # The concentration of IL-8 in the absence of a pathogen
q_IL10 = 0.15          # relative concentration                                # The concentration of IL-10 in the absence of a pathogen
q_TNF = 0.14           # relative concentration                                # The concentration of TNF-a in the absence of a pathogendescription

"""## Parameters by Pritchard-Bell, Ari  (2016):"""

# Cortisol parameters - Best values

ktc  = 3.43/60      # ng/(pg·h) # The magnitude of cortisol activation by TNF
kmct = 86.9         # ng/mL       # 
kmtc = 27.8         # pg/mL       # 
kcd  = 0.0155/60    # h^-1        # Cortisol degradation
klt = 43.5/60       # h^-1

"""## Parameters by Quintela et al., (2014):"""

# In Reference: beta_A = 2
beta_A = 0.02                   # 1/day           # Replication rate of the bacteria
k_A = 50.0                      # mm^3/day        # Carrying capacity of the bacteria
#In Reference: m_A = 0.1
m_A = 0.9                        # 1/day          # Natural decay rate of the bacteria
m_Mr = 0.033                     # 1/day          # Natural decay rate of the resting macrophages
m_Ma = 0.07                      # 1/day          # Natural decay rate of the activated macrophages

"""## Initial Conditions by experimental data:"""

A = 2                  # Cell/mm3 # S. aureus Bacteria               
MA = 5                 #  -       # Macrophages activated
MR = 10                # Cell/mm3 # Macrophages resting
IL_6 = 0               #          # Interleukin-6 (pro-inflammatory)
IL_8 = 0               #          # Interleukin-8 (pro-inflammatory)
IL_10 = 0.7            #          # Interleukin-10 (anti-inflammatory)
TNF = 0.17             #          # Tumor Necrosis Factor a (pro-inflammatory)     
MR_max = 5             #          # Macrophages resting max  
COR = 10               #          # Test value to Cortisol

#BARBARA TEST
'''
A = 20                  # Cell/mm3 # S. aureus Bacteria               
MA = 0                 #  -       # Macrophages activated
MR = 25                # Cell/mm3 # Macrophages resting
IL_6 = 0               #          # Interleukin-6 (pro-inflammatory)
IL_8 = 0               #          # Interleukin-8 (pro-inflammatory)
IL_10 = 0.7            #          # Interleukin-10 (anti-inflammatory)
TNF = 0.17             #          # Tumor Necrosis Factor a (pro-inflammatory)     
MR_max = 5             #          # Macrophages resting max  
COR = 20               #          # Test value to Cortisol
'''
# Initial Conditions of Each Equation
y0 = [A, MA, MR, IL_10, IL_6, IL_8, TNF, COR]

# Simulation Parameters
sim_time = 1         # day        # Total time of simulation in min 
deltaT = pow(10, -4) # -          # Step size

t = np.arange(0,sim_time,deltaT)

"""#**First scenario:**

## Considering the influence of Cortisol on the TNF equation
__________________________________________________________

## ODE System
"""

def f(y, t):
    A = y[0]
    MA = y[1]
    MR = y[2]
    IL10 = y[3]
    IL6 = y[4]
    IL8 = y[5]
    TNF = y[6]
    COR = y[7]
    

    dAdt = (beta_A * A *(1 - (A / k_A)) - m_A * A * MA)
    
    dMAdt = ((k_m + k_MTNF * pow(TNF, h_MTNF) / (pow(n_MTNF, h_MTNF) + pow(TNF, h_MTNF)) * (pow(n_M10, h_M10) / (pow(n_M10, h_M10)\
         + pow(IL10, h_M10)))) * MR * A - k_MA * MA)
    
    dMRdt = ((-(k_m + k_MTNF * (pow(TNF, h_MTNF) / (pow(n_MTNF, h_MTNF) + pow(TNF, h_MTNF))) * (pow(n_M10, h_M10) / (pow(n_M10, h_M10)\
         + pow(IL10, h_M10)))) * MR * A + k_MR * MR) + k_MR * MR * (1 - MR / MR_max))
       
    dIL10dt = ((k_10m + k_106 * (pow(IL6, h_106) / (pow(n_106, h_106) + pow(IL6, h_106)))) * MA - k_10 * (IL10 - q_IL10))
    
    dIL6dt = ((k_6m + k_6TNF * (pow(TNF, h_6TNF) / (pow(n_6TNF, h_6TNF) + pow(TNF, h_6TNF))) * (pow(n_66, h_66) / (pow(n_66, h_66)\
         + pow(IL6, h_66))) * (pow(n_610, h_610) / (pow(n_610, h_610) + pow(IL10, n_610)))) * MA - k_6 * (IL6 - q_IL6))
    
    dIL8dt = ((k_8m + k_8TNF * (pow(TNF, h_8TNF) / (pow(TNF, h_8TNF) + pow(n_8TNF, h_8TNF))) * (pow(n_810, h_810) / (pow(n_810, h_810)\
         + pow(IL10, h_810)))) * MA - k_8 * (IL8 - q_IL8))
    
    dTNFdt = ((k_TNFM * (pow(n_TNF6, h_TNF6) / (pow(n_TNF6, h_TNF6) \
              + pow(IL6, h_TNF6))) * (pow(n_TNF10, h_TNF10) / (pow(n_TNF10, h_TNF10)\
              + pow(IL10, h_TNF10)))) * MA - klt*A*(1-COR/(COR+kmct)) - k_TNF * (TNF - q_TNF))
    
    #dTNFdt = ((k_TNFM * (pow(n_TNF6, h_TNF6) / (pow(n_TNF6, h_TNF6) \
    #          + pow(IL6, h_TNF6))) * (pow(n_TNF10, h_TNF10) / (pow(n_TNF10, h_TNF10)\
    #         + pow(IL10, h_TNF10)))) * MA *klt*A*COR- k_TNF * (TNF - q_TNF))

    dCORdt = ktc * TNF/(TNF + kmtc) - kcd*COR     
    #dCORdt = ktc*TNF- kcd*COR

    return [dAdt, dMAdt, dMRdt, dIL10dt, dIL6dt, dIL8dt, dTNFdt, dCORdt]

# Solution with odeint() function
sol = odeint(f, y0, t)
out_A = sol[:, 0]
out_MA = sol[:, 1]
out_MR = sol[:, 2]
out_IL10 = sol[:, 3]
out_IL6 = sol[:, 4]
out_IL8 = sol[:, 5]
out_TNF = sol[:, 6]
out_COR = sol[:, 7]

tnf_with_cortisol = []
tnf_with_cortisol = out_TNF

# Normalization
out_TNF = 100 * (out_TNF - min(out_TNF)) / (max(out_TNF) - min(out_TNF))
out_IL6 = 100 * (out_IL6 - min(out_IL6)) / (max(out_IL6) - min(out_IL6))
out_IL8 = 100 * (out_IL8 - min(out_IL8)) / (max(out_IL8) - min(out_IL8))
out_IL10 = 100 * (out_IL10 - min(out_IL10)) / (max(out_IL10) - min(out_IL10))

"""## Plots: """
'''
fig, (ax1, ax2) = plt.subplots(1,2)

# Cytokines
ax1.plot(t, out_TNF,'purple', label="TNF α")
ax1.plot(t, out_IL6, 'b', label="IL-6")
ax1.plot(t, out_IL8, 'r--', label="IL-8")
ax1.plot(t, out_IL10, 'orange', label="IL-10")

ax1.set_title("Cytokines", fontsize = 20)
ax1.legend( ncol = 4, bbox_to_anchor = (0.5,-0.13), loc='upper center', fontsize = 11)
ax1.set_xlabel('Time (days)', fontsize = 13)
ax1.set_ylabel('Cytokine concentrations \n (relative values)', fontsize = 13)

# S. aureus
ax2.plot(t, out_MR, 'b--', label="MR")
ax2.plot(t, out_MA, 'black', label="MA")
ax2.plot(t, out_A,'r', label="A")

ax2.set_title("S. aureus", fontsize = 20)
ax2.legend( ncol = 4, bbox_to_anchor = (0.5,-0.13), loc='upper center', fontsize = 11)
ax2.set_xlabel('Time (days)', fontsize = 13)
ax2.set_ylabel('Macrophage Concentration and S. aureus \n (cells/mm3 )', fontsize = 13)


fig.set_figwidth(15) 
fig.set_figheight(6) 
fig.tight_layout()
#plt.show()
print("\n\n\n")


fig, (ax3, ax4) = plt.subplots(1,2)

# Cortisol
ax3.set_ylabel('Cortisol (ng/day)')
ax3.plot(t, out_COR,'g' , marker = '+', label="COR")
ax3.set_title("Cortisol", fontsize = 20)
ax3.legend( ncol = 4, bbox_to_anchor = (0.5,-0.13), loc='upper center', fontsize = 11)
ax3.set_xlabel('Time (days)', fontsize = 13)

# TNF
ax4.set_title("TNF", fontsize = 20)
ax4.plot(t, tnf_with_cortisol,'purple', marker='+',label="TNF-α with cortisol")
ax4.legend( ncol = 4, bbox_to_anchor = (0.5,-0.13), loc='upper center', fontsize = 11)
ax4.set_xlabel('Time (days)', fontsize = 13)

fig.set_figwidth(15) 
fig.set_figheight(6) 
fig.tight_layout()
plt.show()'''

"""# **Second Scenario:**
### Disregarding the influence of Cortisol on the TNF ODE
__________________________________________________________________________________________________________
"""

#MODEL WITHOUT CORTISOL INFLUENCE
# /*******************************************************************************
#  * @param y - equations of simulation
#  * @param t - evenly spaced array with time of simulation
#  ******************************************************************************/
def f2(y2, t):
    A2 = y2[0]
    MA2 = y2[1]
    MR2= y2[2]
    IL102 = y2[3]
    IL62 = y2[4]
    IL82 = y2[5]
    TNF2 = y2[6]
    COR2 = y2[7]
    

    dAdt2 = (beta_A * A2 *(1 - (A2 / k_A)) - m_A * A2 * MA2)
    
    dMAdt2 = ((k_m + k_MTNF * pow(TNF2, h_MTNF) / (pow(n_MTNF, h_MTNF) + pow(TNF2, h_MTNF)) * (pow(n_M10, h_M10) / (pow(n_M10, h_M10)\
         + pow(IL102, h_M10)))) * MR2 * A2 - k_MA * MA2)
    
    dMRdt2 = ((-(k_m + k_MTNF * (pow(TNF2, h_MTNF) / (pow(n_MTNF, h_MTNF) + pow(TNF2, h_MTNF))) * (pow(n_M10, h_M10) / (pow(n_M10, h_M10)\
         + pow(IL102, h_M10)))) * MR2 * A2 + k_MR * MR2) + k_MR * MR2 * (1 - MR2 / MR_max))
       
    dIL10dt2 = ((k_10m + k_106 * (pow(IL62, h_106) / (pow(n_106, h_106) + pow(IL62, h_106)))) * MA2 - k_10 * (IL102 - q_IL10))
    
    dIL6dt2 = ((k_6m + k_6TNF * (pow(TNF2, h_6TNF) / (pow(n_6TNF, h_6TNF) + pow(TNF2, h_6TNF))) * (pow(n_66, h_66) / (pow(n_66, h_66)\
         + pow(IL62, h_66))) * (pow(n_610, h_610) / (pow(n_610, h_610) + pow(IL102, n_610)))) * MA2 - k_6 * (IL62 - q_IL6))
    
    dIL8dt2 = ((k_8m + k_8TNF * (pow(TNF2, h_8TNF) / (pow(TNF2, h_8TNF) + pow(n_8TNF, h_8TNF))) * (pow(n_810, h_810) / (pow(n_810, h_810)\
         + pow(IL102, h_810)))) * MA2 - k_8 * (IL82 - q_IL8))
    
    #dTNFdt2 = ((k_TNFM * (pow(n_TNF6, h_TNF6) / (pow(n_TNF6, h_TNF6) \
    #          + pow(IL6, h_TNF6))) * (pow(n_TNF10, h_TNF10) / (pow(n_TNF10, h_TNF10)\
    #          + pow(IL10, h_TNF10)))) * MA - klt*A*(1-COR/(COR+kmct)) - k_TNF * (TNF - q_TNF))
    
    #dTNFdt2 = ((k_TNFM * (pow(n_TNF6, h_TNF6) / (pow(n_TNF6, h_TNF6) \
    #          + pow(IL6, h_TNF6))) * (pow(n_TNF10, h_TNF10) / (pow(n_TNF10, h_TNF10)\
    #         + pow(IL10, h_TNF10)))) * MA *COR * klt *A - k_TNF * (TNF - q_TNF))

    dTNFdt2 = ((k_TNFM * (pow(n_TNF6, h_TNF6) / (pow(n_TNF6, h_TNF6) \
              + pow(IL62, h_TNF6))) * (pow(n_TNF10, h_TNF10) / (pow(n_TNF10, h_TNF10)\
             + pow(IL102, h_TNF10)))) * MA2 - k_TNF * (TNF2 - q_TNF))

    dCORdt2 = ktc * TNF2/(TNF2 + kmtc) - kcd*COR2     
    #dCORdt = ktc*TNF- kcd*COR

    return [dAdt2, dMAdt2, dMRdt2, dIL10dt2, dIL6dt2, dIL8dt2, dTNFdt2, dCORdt2]

# Solution with odeint() function
sol2 = odeint(f2, y0, t)
out_A2 = sol2[:, 0]
out_MA2 = sol2[:, 1]
out_MR2 = sol2[:, 2]
out_IL102 = sol2[:, 3]
out_IL62 = sol2[:, 4]
out_IL82 = sol2[:, 5]
out_TNF2 = sol2[:, 6]
out_COR2 = sol2[:, 7]

tnf_without_cortisol = []
tnf_without_cortisol = out_TNF2

# Normalization
out_TNF2 = 100 * (out_TNF - min(out_TNF)) / (max(out_TNF) - min(out_TNF))
out_IL62 = 100 * (out_IL6 - min(out_IL6)) / (max(out_IL6) - min(out_IL6))
out_IL82 = 100 * (out_IL8 - min(out_IL8)) / (max(out_IL8) - min(out_IL8))
out_IL102 = 100 * (out_IL10 - min(out_IL10)) / (max(out_IL10) - min(out_IL10))

fig, (ax1, ax2) = plt.subplots(1,2)

# Cytokines
ax1.plot(t, out_TNF2,'purple', label="TNF α")
ax1.plot(t, out_IL62, 'b', label="IL-6")
ax1.plot(t, out_IL82, 'r--', label="IL-8")
ax1.plot(t, out_IL102, 'orange', label="IL-10")

ax1.set_title("Cytokines", fontsize = 20)
ax1.legend( ncol = 4, bbox_to_anchor = (0.5,-0.13), loc='upper center', fontsize = 11)
ax1.set_xlabel('Time (days)', fontsize = 13)
ax1.set_ylabel('Cytokine concentrations \n (relative values)', fontsize = 13)

# S. aureus
ax2.plot(t, out_MR2, 'b--', label="MR")
ax2.plot(t, out_MA2, 'black', label="MA")
ax2.plot(t, out_A2,'r', label="A")

ax2.set_title("S. aureus", fontsize = 20)
ax2.legend( ncol = 4, bbox_to_anchor = (0.5,-0.13), loc='upper center', fontsize = 11)
ax2.set_xlabel('Time (days)', fontsize = 13)
ax2.set_ylabel('Macrophage Concentration and S. aureus \n (cells/mm3 )', fontsize = 13)

fig.set_figwidth(15) 
fig.set_figheight(6) 
fig.tight_layout()
#plt.show()
print("\n\n\n")

fig, (ax3, ax4) = plt.subplots(1,2)

# Cortisol
ax3.set_ylabel('Cortisol (ng/day)')
ax3.plot(t, out_COR2,'g' , marker = '+', label="COR")
ax3.set_title("Cortisol", fontsize = 20)
ax3.legend( ncol = 4, bbox_to_anchor = (0.5,-0.13), loc='upper center', fontsize = 11)
ax3.set_xlabel('Time (days)', fontsize = 13)

# TNF's
ax4.set_title("TNF's", fontsize = 20)
ax4.plot(t, tnf_with_cortisol,'purple', marker='+',label="TNF α with cortisol")
ax4.plot(t, tnf_without_cortisol,'red', label="TNF α without cortisol")
ax4.legend( ncol = 4, bbox_to_anchor = (0.5,-0.13), loc='upper center', fontsize = 11)
ax4.set_xlabel('Time (days)', fontsize = 13)

fig.set_figwidth(15) 
fig.set_figheight(6) 
fig.tight_layout()
plt.show()
plt.savefui